name: compile

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-10.15
    steps:
    - name: Install CVMFS
      run: |
        cd
        brew cask install osxfuse
        curl -L -o ~/cvmfs-2.7.1.pkg https://ecsft.cern.ch/dist/cvmfs/cvmfs-2.7.1/cvmfs-2.7.1.pkg
        sudo installer -package cvmfs-2.7.1.pkg -target /
        mkdir -p /Users/Shared/cvmfs/sft.cern.ch
        wget --no-check-certificate https://lcd-data.web.cern.ch/lcd-data/CernVM/default.local
        sudo mv default.local /etc/cvmfs/default.local
        sudo cvmfs_config setup
        brew install gfortran
    - name: test CVMFS
      run: |
        sudo mount -t cvmfs sft.cern.ch /Users/Shared/cvmfs/sft.cern.ch
        ls /Users/Shared/cvmfs/sft.cern.ch
        source /Users/Shared/cvmfs/sft.cern.ch/lcg/views/LCG_97apython3/x86_64-mac1015-clang110-opt/setup.sh
        root-config --cflags
