name: compile

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-10.15
    steps:
    - name: Install CVMFS
      run: |
        cd
        brew cask install osxfuse
        curl -L -o ~/cvmfs-2.7.1.pkg https://ecsft.cern.ch/dist/cvmfs/cvmfs-2.7.1/cvmfs-2.7.1.pkg
        sudo installer -package cvmfs-2.7.1.pkg -target /
        wget --no-check-certificate https://lcd-data.web.cern.ch/lcd-data/CernVM/default.local
        sudo mv default.local /etc/cvmfs/default.local
        sudo cvmfs_config setup
        brew cask install gfortran
        brew cask install xquartz
    - name: test CVMFS
      run: |
        mkdir -p /Users/Shared/cvmfs/sft.cern.ch
        mkdir -p /Users/Shared/cvmfs/geant4.cern.ch
        sudo mount -t cvmfs sft.cern.ch /Users/Shared/cvmfs/sft.cern.ch
        sudo mount -t cvmfs geant4.cern.ch /Users/Shared/cvmfs/geant4.cern.ch
        ls /Users/Shared/cvmfs/sft.cern.ch
        ls /Users/Shared/cvmfs/geant4.cern.ch
        source /Users/Shared/cvmfs/sft.cern.ch/lcg/views/LCG_97apython3/x86_64-mac1015-clang110-opt/setup.sh
        root-config --cflags
        git clone https://github.com/petricm/DD4hep.git
        cd DD4hep
        export CXX=clang++
        export CC=clang
        export FC=""
        mkdir build
        cd build
        cmake -GNinja -DDD4HEP_USE_GEANT4=ON -DBoost_NO_BOOST_CMAKE=ON -DDD4HEP_USE_LCIO=ON -DBUILD_TESTING=ON -DGeant4_DIR=$G4INSTALL/lib/Geant4-10.6.1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 ..
        ninja
        ninja install
        . ../bin/thisdd4hep.sh
        ctest --output-on-failure -j4
        cd ../examples/
        mkdir build
        cd build
        cmake -GNinja -DBoost_NO_BOOST_CMAKE=ON -DCMAKE_CXX_STANDARD=17 ..
        ninja
        ninja install
        ctest --output-on-failure
