name: compile

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-10.15
    steps:
    - name: Install CVMFS
      run: |
        cd
        curl -L -o ~/cvmfs-2.7.1.pkg https://ecsft.cern.ch/dist/cvmfs/cvmfs-2.7.1/cvmfs-2.7.1.pkg
        curl -L -o ~/osxfuse-3.10.4.dmg https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.10.4/osxfuse-3.10.4.dmg
        sudo hdiutil attach osxfuse-3.10.4.dmg
        sudo installer -package /Volumes/FUSE\ for\ macOS/FUSE\ for\ macOS.pkg -target /
        sudo hdiutil detach /Volumes/FUSE\ for\ macOS
        sudo installer -package cvmfs-2.7.1.pkg -target /
        mkdir -p /Users/Shared/cvmfs/sft.cern.ch
    - name: Install CVMFS
      run: |
        sudo mount -t cvmfs sft.cern.ch /cvmfs/sft.cern.ch
        ls /cvmfs/sft.cern.ch
